auto:       true

lsi:        true
markdown:   rdiscount
permalink:  /:title.html

info:
    title:              'Duke Nukem まとめサイト'
    author:             'Japboy'
    author-contact:     'http://twitter.com/japboy'
    rights:             'Public domain'
    rights-standard:    'pd'
